### ISSUE TITLE
No menu

### ISSUE THREAD

**Issue by SuperDuper77** [ALEX5402/LIb-fire#1]
Menu not loaded up

**Comment by ALEX5402** [comment]
please provide logs with android version

**Comment by SuperDuper77** [comment]
Not on PC rn, logs say something Lib not found when its there. Wait.. does it need to be matched x86_64 lib if test on LD9?

**Comment by ALEX5402** [comment]
> Not on PC rn, logs say something Lib not found when its there. Wait.. does it need to be matched x86_64 lib if test on LD9?

oh just load the lib from anywhere elso like /tmp or /sdcard any other path like this 

but don't use apk's private folders like data dir or lib dir because it woun't worked with Yukki idk why but you can load the lib from anywhere else before calling the menu if you need that feature then make a feature request

**Comment by xAffan** [comment]
> > Not on PC rn, logs say something Lib not found when its there. Wait.. does it need to be matched x86_64 lib if test on LD9?
> 
> oh just load the lib from anywhere elso like /tmp or /sdcard any other path like this
> 
> but don't use apk's private folders like data dir or lib dir because it woun't worked with Yukki idk why but you can load the lib from anywhere else before calling the menu if you need that feature then make a feature request

It sends the context of the hooked application. The hooked application can't load library from another application so it fails.
